package resolvers

import (
	"github.com/haunted-saas/graphql-api-gateway/internal/clients"
	"go.uber.org/zap"
)

// This file will be generated by gqlgen, but we define the base resolver here

// Resolver is the root resolver
type Resolver struct {
	clients *clients.GRPCClients
	logger  *zap.Logger
}

// NewResolver creates a new resolver
func NewResolver(clients *clients.GRPCClients, logger *zap.Logger) *Resolver {
	return &Resolver{
		clients: clients,
		logger:  logger,
	}
}
